// =============================================================================
// plover_hello.cc — host-side test routines.
//
// The actual register access is via the peakrdl-cpp generated headers (one
// per unit), which expose a typed class hierarchy. A small BusAdapter wraps
// the host_ops callbacks so the generated templated code can call
// adapter.read(addr) / adapter.write(addr, val); the adapter forwards each
// call into the right host_ops function pointer.
//
// Net effect: the firmware reads registers by name and accesses fields
// directly (`shell.ID.VALUE.read()`) rather than passing literal addresses.
// =============================================================================
#include "plover_hello.h"

#include "axil_shell_regs.hh"   // generated by peakrdl-cpp; one per RDL unit
#include "syscon_regs.hh"

#include <cstdarg>
#include <cstdio>

namespace {

// Tiny bus adapter that satisfies peakrdl-cpp's BusT concept:
//   data_t read(addr_t addr);
//   void   write(addr_t addr, data_t value);
//
// It just forwards to the C function pointers in plover_host_ops, plus
// remembers which slave's callbacks to use (shell vs. syscon). One instance
// per slave; we keep them on the stack of plover_hello_world.
class BusAdapter {
public:
    BusAdapter(plover_read_fn read_fn, plover_write_fn write_fn)
        : read_fn_(read_fn), write_fn_(write_fn) {}

    uint32_t read(uint32_t addr)                  { return read_fn_(addr); }
    void     write(uint32_t addr, uint32_t value) { write_fn_(addr, value); }

private:
    plover_read_fn  read_fn_;
    plover_write_fn write_fn_;
};

void log_msg(const plover_host_ops* ops, const char* fmt, ...) {
    if (!ops || !ops->log) {
        return;
    }
    char buf[256];
    va_list args;
    va_start(args, fmt);
    vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    ops->log(buf);
}

constexpr uint32_t kShellIdExpected = 0xC0C07B01u;

}  // namespace

extern "C" int plover_hello_world(const plover_host_ops* ops,
                                  uint32_t expected_syscon_version) {
    if (!ops || !ops->shell_read || !ops->shell_write
             || !ops->syscon_read || !ops->syscon_write) {
        return -1;  // misconfigured host
    }

    BusAdapter shell_bus(ops->shell_read, ops->shell_write);
    BusAdapter syscon_bus(ops->syscon_read, ops->syscon_write);

    // Build the typed chip views. Each is templated on the bus adapter, so
    // there's no runtime virtual dispatch — the compiler inlines straight
    // through into the read_fn / write_fn callbacks. Each generated header
    // owns its own namespace (one per RDL unit) so they can coexist in the
    // same translation unit; peakrdl-cpp emits common scope-level helpers
    // inside the namespace, so a shared namespace across units would
    // collide on those definitions.
    axil_shell_regs::axil_shell<BusAdapter> shell(shell_bus, /*base=*/0);
    syscon_regs::syscon<BusAdapter>         syscon(syscon_bus, /*base=*/0);

    // ---- axil_shell ID ----
    log_msg(ops, "plover firmware: reading axil_shell.ID via typed accessor");
    const uint32_t id_value = shell.ID.VALUE.read();
    if (id_value != kShellIdExpected) {
        log_msg(ops, "FAIL: axil_shell.ID.VALUE = 0x%08x, expected 0x%08x",
                id_value, kShellIdExpected);
        return 1;
    }
    log_msg(ops, "OK: axil_shell.ID.VALUE = 0x%08x", id_value);

    // ---- syscon VERSION ----
    log_msg(ops, "plover firmware: reading syscon.VERSION via typed accessor");
    const uint32_t version = syscon.VERSION.read();
    if (version != expected_syscon_version) {
        log_msg(ops, "FAIL: syscon.VERSION = 0x%08x, expected 0x%08x",
                version, expected_syscon_version);
        return 2;
    }
    log_msg(ops, "OK: syscon.VERSION = 0x%08x", version);

    log_msg(ops, "plover firmware: hello world complete");
    return 0;
}
