/* =============================================================================
 * plover_hello.h
 *
 * Host-side "firmware" library API. The C test routines here treat the chip
 * as a register file behind two AXI4-Lite slaves and operate on it through
 * callbacks supplied by the host environment (e.g. the cocotb testbench at
 * the bottom of the simulator). The same source could later cross-compile
 * and run on a real CPU mastering AXI on a board — the C stays the same;
 * only the read/write implementations change.
 *
 * Plain C ABI throughout: ctypes (Python side) loads and calls into this
 * library directly, no binding-generator layer.
 *
 * The actual register-access layer is generated by PeakRDL-cheader from
 * each unit's .rdl file (axil_shell_regs.h, syscon_regs.h). Those headers
 * provide a packed struct mirroring the register layout (used here with
 * offsetof) and per-field bm/bp/bw macros for bitfield extraction.
 * ============================================================================= */
#ifndef PLOVER_HELLO_H
#define PLOVER_HELLO_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Callback function pointer types. Each operates on a single 32-bit word
 * at the given byte offset on the named AXI-Lite slave. */
typedef uint32_t (*plover_read_fn) (uint32_t addr);
typedef void     (*plover_write_fn)(uint32_t addr, uint32_t data);

/* Host environment passes one of these in when calling the test routines.
 * shell_* talks to the axil_shell slave (s_axil_* at the plover top
 * boundary); syscon_* talks to the syscon slave (s_syscon_*). */
typedef struct {
    plover_read_fn  shell_read;
    plover_write_fn shell_write;
    plover_read_fn  syscon_read;
    plover_write_fn syscon_write;
    /* Optional logger: if non-NULL, the test routines call this with
     * human-readable progress strings. Bound to the cocotb logger by the
     * Python bridge. */
    void (*log)(const char* msg);
} plover_host_ops;

/* Returns 0 on success, non-zero on the first failing check.
 *
 * Reads two known-value registers (axil_shell.ID and syscon.VERSION) via
 * the host callbacks and confirms each matches expectations. The shell ID
 * value is a build-time constant (0xC0C07B01) baked into the RTL; the
 * syscon VERSION is supplied as an argument so the Python bridge can pass
 * the same value it tells the Verilator build to use, keeping this C side
 * simulator-agnostic. */
int plover_hello_world(const plover_host_ops* ops, uint32_t expected_syscon_version);

#ifdef __cplusplus
}
#endif

#endif /* PLOVER_HELLO_H */
