/* =============================================================================
 * plover_hello.c — host-side test routines, plain C.
 *
 * After the project-top xbar refactor the host sees a single AXI-Lite
 * port; each peripheral lives at a page base on that bus. Register
 * addresses are therefore computed as:
 *
 *      <page_base> + offsetof(<unit>_t, <register>)
 *
 * which keeps the RDL as the single source of truth for register offsets
 * (via the packed struct emitted by peakrdl-cheader) and lets the host
 * environment relocate any peripheral by passing a different page base.
 *
 * Bitfields within registers are still extracted with the generator's
 * _bm/_bp macros.
 *
 * No platform headers, no simulator hooks: all host coupling is through
 * the plover_host_ops struct of function pointers, so the same .c could
 * later cross-compile to run on a real CPU board with a different
 * read/write implementation.
 * ============================================================================= */
#include "plover_hello.h"

#include "axil_shell_regs.h"   /* generated by peakrdl-cheader; one per RDL unit */
#include "syscon_regs.h"

#include <stdarg.h>
#include <stddef.h>
#include <stdio.h>

/* Byte offset of a register field within its register block. Uses the
 * packed struct emitted by peakrdl-cheader so a typo in the field name
 * fails at compile time rather than runtime. */
#define REG_OFFSET(type, field) ((uint32_t)offsetof(type, field))

/* Absolute bus address of a register: page base + register offset. */
#define REG_ADDR(base, type, field) ((base) + REG_OFFSET(type, field))

/* Extract a field from a raw register value using the bm/bp macros that
 * peakrdl-cheader generates. The macros are formed as
 *   <UNIT>__<REG>__<FIELD>_bm   (bitmask in-place)
 *   <UNIT>__<REG>__<FIELD>_bp   (bit position)
 * Call site:  FIELD_GET(raw, AXIL_SHELL__ID__VALUE) */
#define FIELD_GET(raw, prefix) (((raw) & prefix##_bm) >> prefix##_bp)

/* Known-constant chip ID baked into the axil_shell RTL. The RDL declares
 * the reset value, but the firmware needs the literal to compare against,
 * so we restate it here with a _Static_assert pinning it to the generated
 * reset macro. Any RDL change that moves the ID's reset value will fail
 * the build (not just the test). */
#define EXPECTED_SHELL_ID 0xC0C07B01u
_Static_assert(EXPECTED_SHELL_ID == AXIL_SHELL__ID__VALUE_reset,
               "EXPECTED_SHELL_ID drifted from the RDL's declared reset value");

static void log_msg(const plover_host_ops* ops, const char* fmt, ...) {
    if (!ops || !ops->log) {
        return;
    }
    char buf[256];
    va_list args;
    va_start(args, fmt);
    vsnprintf(buf, sizeof(buf), fmt, args);
    va_end(args);
    ops->log(buf);
}

int plover_hello_world(const plover_host_ops* ops,
                       uint32_t shell_base,
                       uint32_t syscon_base,
                       uint32_t expected_syscon_version) {
    if (!ops || !ops->read || !ops->write) {
        return -1;  /* misconfigured host */
    }

    /* ---- axil_shell.ID ---- */
    const uint32_t id_addr = REG_ADDR(shell_base, axil_shell_t, ID);
    const uint32_t id_raw  = ops->read(id_addr);
    const uint32_t id_value = FIELD_GET(id_raw, AXIL_SHELL__ID__VALUE);
    log_msg(ops, "plover firmware: read axil_shell.ID @ 0x%08x -> raw=0x%08x value=0x%08x",
            id_addr, id_raw, id_value);
    if (id_value != EXPECTED_SHELL_ID) {
        log_msg(ops, "FAIL: axil_shell.ID.VALUE = 0x%08x, expected 0x%08x",
                id_value, EXPECTED_SHELL_ID);
        return 1;
    }

    /* ---- syscon.VERSION ----
     * The full 32-bit register matches the override the host passes in.
     * No bitfield extraction; the caller knows what value to expect. */
    const uint32_t version_addr = REG_ADDR(syscon_base, syscon_t, VERSION);
    const uint32_t version = ops->read(version_addr);
    log_msg(ops, "plover firmware: read syscon.VERSION @ 0x%08x -> 0x%08x",
            version_addr, version);
    if (version != expected_syscon_version) {
        log_msg(ops, "FAIL: syscon.VERSION = 0x%08x, expected 0x%08x",
                version, expected_syscon_version);
        return 2;
    }

    log_msg(ops, "plover firmware: hello world complete");
    return 0;
}

int plover_program_fir(const plover_host_ops* ops,
                       uint32_t fir_base,
                       const int32_t* coefs,
                       uint32_t n_taps,
                       int verify_readback) {
    if (!ops || !ops->read || !ops->write || !coefs) {
        return -1;
    }
    log_msg(ops, "plover firmware: programming FIR @ 0x%08x with %u tap(s)",
            fir_base, n_taps);
    for (uint32_t i = 0; i < n_taps; i++) {
        const uint32_t addr = fir_base + 4u * i;
        /* The FIR's RTL latches the low COEF_W bits and ignores the
         * rest, so just writing the raw int32_t works regardless of
         * the COEF_W choice (8/12/16/24/32). Cast through uint32_t to
         * avoid implementation-defined behaviour on negative shift. */
        const uint32_t data = (uint32_t)coefs[i];
        ops->write(addr, data);
    }
    if (verify_readback) {
        for (uint32_t i = 0; i < n_taps; i++) {
            const uint32_t addr   = fir_base + 4u * i;
            const uint32_t got    = ops->read(addr);
            const uint32_t expect = (uint32_t)coefs[i];
            if (got != expect) {
                log_msg(ops,
                        "FAIL: FIR coef[%u] readback = 0x%08x, expected 0x%08x",
                        i, got, expect);
                return (int)(10 + i);  /* distinct rc per tap */
            }
        }
        log_msg(ops, "plover firmware: FIR coef readback OK (%u taps)", n_taps);
    }
    return 0;
}
