// =============================================================================
// plover_hello.h
//
// Host-side "firmware" library API. The C++ test routines here treat the
// chip as a register file behind two AXI4-Lite slaves and operate on it
// through callbacks supplied by the host environment (e.g. the cocotb
// testbench at the bottom of the simulator).
//
// The actual *register-access* layer is generated by PeakRDL-cpp from each
// unit's .rdl file, so the firmware code reads like
// `shell.ID.read()` rather than `host_ops.shell_read(0x0C)`. The plumbing
// here is just the callback contract that turns those typed accesses into
// real bus transactions; the firmware itself is in plover_hello.cc.
//
// Everything declared here is plain C ABI so ctypes (Python side) can load
// and call it without a binding-generator layer.
// =============================================================================
#ifndef PLOVER_HELLO_H
#define PLOVER_HELLO_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

// Callback function pointer types. Each operates on a single 32-bit word
// at the given byte offset on the named AXI-Lite slave.
typedef uint32_t (*plover_read_fn) (uint32_t addr);
typedef void     (*plover_write_fn)(uint32_t addr, uint32_t data);

// Host environment passes one of these in when calling the test routines.
// shell_* talks to the axil_shell slave (s_axil_* at the plover top boundary)
// and syscon_* talks to the syscon slave (s_syscon_*).
typedef struct {
    plover_read_fn  shell_read;
    plover_write_fn shell_write;
    plover_read_fn  syscon_read;
    plover_write_fn syscon_write;
    // Optional logger: if non-NULL, the test routines call this with
    // human-readable progress strings. Bound to the cocotb logger by the
    // Python bridge.
    void (*log)(const char* msg);
} plover_host_ops;

// Returns 0 on success, non-zero on the first failing check. The current
// test reads two known-value registers via the generated peakrdl-cpp
// accessors to confirm the host callbacks really reach the chip.
//
// expected_syscon_version is supplied as an argument rather than hard-coded
// so the Python bridge can pass the same value it tells the Verilator build
// to use, keeping the C++ side simulator-agnostic.
int plover_hello_world(const plover_host_ops* ops, uint32_t expected_syscon_version);

#ifdef __cplusplus
}
#endif

#endif // PLOVER_HELLO_H
