/* =============================================================================
 * plover_hello.h
 *
 * Host-side "firmware" library API. After the project-top xbar refactor,
 * all peripheral access goes through a single AXI-Lite master at the top
 * boundary; the host_ops struct correspondingly has just one read/write
 * pair, and the test routines take the peripherals' page bases as
 * arguments so they can address each peripheral by its absolute bus
 * address.
 *
 * The same source could later cross-compile and run on a real CPU
 * mastering AXI on a board — the C stays the same; only the read/write
 * implementations change.
 *
 * Plain C ABI throughout: ctypes (Python side) loads and calls into this
 * library directly, no binding-generator layer.
 *
 * The register-access layer is generated by PeakRDL-cheader from each
 * unit's .rdl file (axil_shell_regs.h, syscon_regs.h). Those headers
 * provide a packed struct mirroring the register layout (used here with
 * offsetof) and per-field bm/bp/bw macros for bitfield extraction.
 * ============================================================================= */
#ifndef PLOVER_HELLO_H
#define PLOVER_HELLO_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Single read/write callback pair. Each operates on a 32-bit word at the
 * given absolute byte address on the host-facing AXI-Lite master at the
 * top of the chip. */
typedef uint32_t (*plover_read_fn) (uint32_t addr);
typedef void     (*plover_write_fn)(uint32_t addr, uint32_t data);

typedef struct {
    plover_read_fn  read;
    plover_write_fn write;
    /* Optional logger: if non-NULL, the test routines call this with
     * human-readable progress strings. Bound to the cocotb logger by the
     * Python bridge. */
    void (*log)(const char* msg);
} plover_host_ops;

/* Returns 0 on success, non-zero on the first failing check.
 *
 * The host passes the page bases at which each peripheral lives on the
 * xbar address map (0x0000_0000 and 0x0000_1000 in plover today). The
 * firmware adds register-file offsets from the generated cheader output
 * to get absolute bus addresses, and uses the single read/write callback
 * pair to access them.
 *
 * Reads two known-value registers (axil_shell.ID and syscon.VERSION) and
 * confirms each matches expectations. The shell ID value is a build-time
 * constant (0xC0C07B01) baked into the RTL; the syscon VERSION is
 * supplied as an argument so the Python bridge can pass the same value
 * it tells the Verilator build to use, keeping this C side
 * simulator-agnostic. */
int plover_hello_world(const plover_host_ops* ops,
                       uint32_t shell_base,
                       uint32_t syscon_base,
                       uint32_t expected_syscon_version);

/* ----------------------------------------------------------------------
 * FIR coefficient bank programming.
 *
 * Programs the FIR filter's coefficient memory with the caller-supplied
 * table. Each tap is one 32-bit AXI-Lite write to (fir_base + 4*i); the
 * FIR's RTL takes the low COEF_W bits and ignores the rest, so passing
 * a sign-extended signed value is the natural shape.
 *
 * Optionally reads each coefficient back via AXI-Lite and verifies the
 * value matches what was written (cheap end-to-end check that the xbar
 * routing and the FIR's read path are wired correctly).
 *
 * The FIR's bank is *not* RDL-described — it's a memory-style slave, so
 * there's no generated header for offsets. The byte offset is just
 * 4*tap_index, which this function computes directly.
 *
 * Coefficient updates are hot — the FIR applies them on the next input
 * sample. Caller is responsible for sequencing relative to the data
 * stream (e.g. mute the stream while reprogramming, or write all coefs
 * back-to-back so the transition is brief).
 *
 * Returns 0 on success, non-zero on the first failing readback (if
 * verify_readback != 0). */
int plover_program_fir(const plover_host_ops* ops,
                       uint32_t fir_base,
                       const int32_t* coefs,
                       uint32_t n_taps,
                       int verify_readback);

#ifdef __cplusplus
}
#endif

#endif /* PLOVER_HELLO_H */
