#!/usr/bin/env python3
"""
Generate a SystemVerilog header carrying build-time version information.

Reads git in the repo containing the .rdl source and emits
``syscon_version_pkg.svh``: a small set of ``define`` macros that the syscon
RTL includes. The RTL still accepts a ``VERSION_OVERRIDE`` parameter
for sim/test, so this header is only consulted when the override is zero.

Convention used here:
* ``git describe --tags --dirty --match v*`` is parsed to pull the closest
  ``vMAJOR.MINOR.PATCH`` tag plus a dirty flag.
* If no matching tag exists, falls back to ``v0.0.0``.
* The 32-bit hash is the lower 32 bits of the abbreviated SHA, parsed as hex.
* If git isn't available at all (tarball build, no .git dir), everything is
  zero and a warning is printed. Builds still work; software just sees
  ``VERSION = 0x00000000`` and ``VERSION_HASH = 0x00000000``.

Run directly:
    python units/syscon/rdl/gen_version.py [--repo <path>] [--out <file>]

Also wired into the FuseSoC ``version_gen`` generator (see syscon.core).
"""
from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path


HEADER_TEMPLATE = """\
// AUTO-GENERATED by units/syscon/rdl/gen_version.py — do not edit by hand.
// Regenerated at build time from git; do not commit.

`ifndef SYSCON_VERSION_PKG_SVH
`define SYSCON_VERSION_PKG_SVH

`define SYSCON_VERSION_MAJOR  8'h{major:02X}
`define SYSCON_VERSION_MINOR  8'h{minor:02X}
`define SYSCON_VERSION_PATCH  8'h{patch:02X}
`define SYSCON_VERSION_DIRTY  1'b{dirty}
`define SYSCON_VERSION_HASH   32'h{hash:08X}

// VERSION register layout: MAJOR[7:0], MINOR[15:8], PATCH[23:16], DIRTY[24],
// RSVD[31:25] = 0. Mirrors the RDL field layout in syscon.rdl.
`define SYSCON_VERSION_VALUE \\
    {{7'h00, `SYSCON_VERSION_DIRTY, `SYSCON_VERSION_PATCH, \\
     `SYSCON_VERSION_MINOR, `SYSCON_VERSION_MAJOR}}

`endif // SYSCON_VERSION_PKG_SVH
"""


def _git(args: list[str], cwd: Path) -> str | None:
    try:
        out = subprocess.run(
            ["git", *args], cwd=cwd, check=True,
            stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True,
        )
        return out.stdout.strip()
    except (FileNotFoundError, subprocess.CalledProcessError):
        return None


def discover_version(repo: Path) -> dict:
    """Returns major/minor/patch/dirty/hash dict; zeros if git unavailable."""
    # Closest matching tag with dirty marker. --always falls back to a bare
    # hash if no tag is present.
    desc = _git(["describe", "--tags", "--dirty", "--match", "v*", "--always"], repo)
    short = _git(["rev-parse", "--short=8", "HEAD"], repo)

    if desc is None and short is None:
        print(f"[gen_version] warning: no git info available in {repo}; "
              f"version registers will read 0x00000000.", file=sys.stderr)
        return dict(major=0, minor=0, patch=0, dirty=0, hash=0)

    dirty = 1 if (desc and desc.endswith("-dirty")) else 0

    # Try to extract vMAJOR.MINOR.PATCH from describe. If only a hash came
    # back (no tag), semver stays at zeros but we still record the hash.
    m = re.search(r"v(\d+)\.(\d+)\.(\d+)", desc or "")
    if m:
        major, minor, patch = (int(g) for g in m.groups())
    else:
        major = minor = patch = 0

    hash_val = 0
    if short:
        try:
            hash_val = int(short, 16) & 0xFFFFFFFF
        except ValueError:
            hash_val = 0

    return dict(major=major, minor=minor, patch=patch, dirty=dirty, hash=hash_val)


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate syscon version header")
    ap.add_argument("--repo", default=".", type=Path,
                    help="path to the git repo (defaults to cwd)")
    ap.add_argument("--out", default="syscon_version_pkg.svh", type=Path,
                    help="output header path")
    args = ap.parse_args()

    info = discover_version(args.repo.resolve())
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(HEADER_TEMPLATE.format(**info))
    print(f"[gen_version] wrote {args.out}: "
          f"v{info['major']}.{info['minor']}.{info['patch']}"
          f"{'-dirty' if info['dirty'] else ''} "
          f"hash=0x{info['hash']:08X}")


if __name__ == "__main__":
    main()
